on:
  workflow_dispatch:
   inputs:
    tag:
     description: 'Tag'
     required: true
     default: 'v1.1.35'

jobs:
  build:
    name: Renew documentation
    runs-on: ubuntu-latest
    steps:
    - name: Pull new module version
      run: env GO111MODULE=on go get -d "github.com/${GITHUB_REPOSITORY}@${{ github.event.inputs.tag }}"
